"""Generates lib/cornerman/py/unicode.ex from the interpreter's own unicodedata.

Run with the oracle's interpreter (Python 3.12.13, Unicode 15.0.0), from the repository root:

    python3 scripts/gen_unicode.py > lib/cornerman/py/unicode.ex && mix format
"""

import sys
import unicodedata

LAST = 0x10FFFF
PYVER = sys.version.split()[0]
UNIVER = unicodedata.unidata_version


def ranges(points):
    out = []
    for c in points:
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


def fmt(rs):
    return ",\n    ".join(f"{{0x{lo:X}, 0x{hi:X}}}" for lo, hi in rs)


nonprintable = ranges(c for c in range(LAST + 1) if not chr(c).isprintable())

# Every Nd character sits in an aligned run of ten starting at its zero digit.
zeros = []
for c in range(LAST + 1):
    ch = chr(c)
    if unicodedata.category(ch) == "Nd":
        value = unicodedata.decimal(ch)
        if value == 0:
            zeros.append(c)
        assert zeros and c - zeros[-1] == value, hex(c)

TEMPLATE = '''# GENERATED by scripts/gen_unicode.py; do not edit.
#
# Unicode @UNIVER@ (from Python @PYVER@'s unicodedata, the interpreter the pinned oracle runs
# on). OTP 28 ships Unicode 16.0 and has no general-category API, so the tables behind
# Ringer's `str.isprintable()` and `int(str)` come from Python itself.
#
# Regenerate with the oracle's interpreter, from the repository root:
#
#     python3 scripts/gen_unicode.py > lib/cornerman/py/unicode.ex && mix format
#
defmodule Cornerman.Py.Unicode do
  @moduledoc """
  Unicode tables for Python parity, generated from Python @PYVER@ (Unicode @UNIVER@).

    * `printable?/1` is `str.isprintable()` for one code point: false for general categories
      Cc, Cf, Cs, Co, Cn, Zl, Zp and Zs, except that the space U+0020 is printable.
    * `decimal_value/1` is `unicodedata.decimal()` for the Nd characters: their value, or
      `nil` for any other code point.
  """

  # Inclusive ranges of code points for which `str.isprintable()` is false.
  @nonprintable [
    @NONPRINTABLE@
  ]
  @nonprintable_tuple List.to_tuple(@nonprintable)
  @last_range tuple_size(@nonprintable_tuple) - 1

  # The zero digit of every run of ten Nd characters.
  @zeros [@ZEROS@]

  @doc "`str.isprintable()` of one code point."
  @spec printable?(non_neg_integer()) :: boolean()
  def printable?(c) when c in 0x20..0x7E, do: true
  def printable?(c), do: not in_ranges?(c, 0, @last_range)

  defp in_ranges?(_c, lo, hi) when lo > hi, do: false

  defp in_ranges?(c, lo, hi) do
    mid = div(lo + hi, 2)

    case elem(@nonprintable_tuple, mid) do
      {first, _last} when c < first -> in_ranges?(c, lo, mid - 1)
      {_first, last} when c > last -> in_ranges?(c, mid + 1, hi)
      _ -> true
    end
  end

  @doc "The value (0-9) of a Unicode decimal digit, or `nil`."
  @spec decimal_value(non_neg_integer()) :: 0..9 | nil
  def decimal_value(c) when c in ?0..?9, do: c - ?0
  def decimal_value(c) when c < 0x660, do: nil

  for zero <- @zeros, zero > ?0 do
    def decimal_value(c) when c in unquote(zero)..unquote(zero + 9), do: c - unquote(zero)
  end

  def decimal_value(_c), do: nil
end
'''

sys.stdout.write(
    TEMPLATE.replace("@UNIVER@", UNIVER)
    .replace("@PYVER@", PYVER)
    .replace("@NONPRINTABLE@", fmt(nonprintable))
    .replace("@ZEROS@", ", ".join(f"0x{z:X}" for z in zeros))
)
